version: '3'

services:
  ubi_restapi:
    image: igorvirgilio/ubi_restapi:v3
    container_name: ubi_restapi
    build: .
    volumes:
      - ./Docker_restapi:/opt
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
  
  ubi_db:
    image: igorvirgilio/ubi_db:v1
    container_name: ubi_db
    build: .
    volumes:
      - ./Docker_db:/opt
    ports:
      - 5432:5432


