# Generated by Django 3.0.5 on 2020-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
